ARG JAVA_IMAGE_TAG=8
ARG TOMCAT_MAJOR_VERSION=7

FROM alpine:latest
ARG TOMCAT_MAJOR_VERSION

RUN set -x && \
    export DOWNLOAD_ROOT_URL="https://www.apache.org/dyn/closer.cgi?action=download&filename=tomcat/tomcat-$TOMCAT_MAJOR_VERSION/" && \
    export TOMCAT_VERSION=$(wget -qO - "$DOWNLOAD_ROOT_URL" | grep "v$TOMCAT_MAJOR_VERSION" | sed "s@.*v\($TOMCAT_MAJOR_VERSION[^/]*\).*@\1@" | tail -n1)&& \
    export DOWNLOAD_URL="$DOWNLOAD_ROOT_URL/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz" && \
    mkdir apache-tomcat && \
	wget "$DOWNLOAD_URL" -O apache-tomcat.tar.gz && \
	tar -xzvf apache-tomcat.tar.gz --strip 1 -C apache-tomcat && \
	rm -r apache-tomcat/webapps && \
	mkdir -p /apache-tomcat/root && \
	echo "PLAIN TEXT" > /apache-tomcat/root/secret.txt

FROM openjdk:$JAVA_IMAGE_TAG
ARG JAVA_IMAGE_TAG

COPY --from=0 /apache-tomcat /apache-tomcat
# Enable TLSv1.1
RUN ( `# Java 12+` && [ -f "/usr/java/openjdk-$JAVA_IMAGE_TAG/conf/security/java.security" ] && ( echo "jdk.tls.disabledAlgorithms=" >> /usr/java/openjdk-$JAVA_IMAGE_TAG/conf/security/java.security ) ) || \
    ( `# Java 11` && [ -f "/usr/local/openjdk-$JAVA_IMAGE_TAG/conf/security/java.security" ] && ( echo "jdk.tls.disabledAlgorithms=" >> /usr/local/openjdk-$JAVA_IMAGE_TAG/conf/security/java.security ) ) || \
    ( `# Java 8` && [ -f "/usr/local/openjdk-$JAVA_IMAGE_TAG/jre/lib/security/java.security" ] && ( echo "jdk.tls.disabledAlgorithms=" >> /usr/local/openjdk-$JAVA_IMAGE_TAG/jre/lib/security/java.security ) ) || \
    ( `# Java 6, 7, 9, 10` && [ -f "/etc/java-$JAVA_IMAGE_TAG-openjdk/security/java.security" ] && ( echo "jdk.tls.disabledAlgorithms=" >> /etc/java-$JAVA_IMAGE_TAG-openjdk/security/java.security ) ) || \
    ( echo "Unable to locate java.security" && false )

VOLUME /secrets /project
