ARG JAVA_IMAGE_TAG=8
ARG TOMCAT_MAJOR_VERSION=7

FROM alpine:latest
ARG TOMCAT_MAJOR_VERSION

RUN set -x && \
    export DOWNLOAD_ROOT_URL="https://www.apache.org/dyn/closer.cgi?action=download&filename=tomcat/tomcat-$TOMCAT_MAJOR_VERSION/" && \
    export TOMCAT_VERSION=$(wget -qO - "$DOWNLOAD_ROOT_URL" | grep "v$TOMCAT_MAJOR_VERSION" | sed "s@.*v\($TOMCAT_MAJOR_VERSION[^/]*\).*@\1@" | tail -n1)&& \
    export DOWNLOAD_URL="$DOWNLOAD_ROOT_URL/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz" && \
    mkdir apache-tomcat && \
	wget "$DOWNLOAD_URL" -O apache-tomcat.tar.gz && \
	tar -xzvf apache-tomcat.tar.gz --strip 1 -C apache-tomcat && \
	rm -r apache-tomcat/webapps && \
	mkdir -p /apache-tomcat/root && \
	echo "PLAIN TEXT" > /apache-tomcat/root/secret.txt

FROM azul/zulu-openjdk:${JAVA_IMAGE_TAG}
ARG JAVA_IMAGE_TAG
# azul/zulu-openjdk:6 does not set JAVA_HOME; fall back to the known path for that image
ENV JAVA_HOME=${JAVA_HOME:-/usr/lib/jvm/zulu-6-amd64}

COPY --from=0 /apache-tomcat /apache-tomcat
# Enable TLSv1.1: clear both disabled and legacy algorithm lists
RUN JAVA_ROOT="${JAVA_HOME:-/usr/lib/jvm}" && \
    SECURITY_FILE=$(find -L "$JAVA_ROOT" -name java.security 2>/dev/null | head -1) && \
    [ -n "$SECURITY_FILE" ] && \
    echo "jdk.tls.disabledAlgorithms=" >> "$SECURITY_FILE" && \
    echo "jdk.tls.legacyAlgorithms=" >> "$SECURITY_FILE" || \
    ( echo "Unable to locate java.security under $JAVA_ROOT" && false )

VOLUME /secrets /project
